apiVersion: v1
kind: Pod
metadata: 
  name: counter
  labels:
    app: counter
spec: 
  containers: 
    - name: app
      image: dolsam77/counter
      # db와 연결하기위해 환경변수 설정
      env:
      - name: REDIS_HOST
        value: "localhost"
    - name: db
      # docker hub로부터 이미지를 가져온다.
      image: redis