apiVersion: v1
kind: Service
metadata: 
  name: counter-np
spec:
  type: NodePort
  ports:
    # 안에 있는 3000번 포트를 찾아가도록
    - port: 3000
      protocol: TCP
      # 31000으로 연결하면 3000번으로 연결됨.
      nodePort: 31000
    # app: counter, tier: app 인 counter app을 찾는다.
  selector:
    app: counter
    tier: app